---
# YAML reference:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema
#
# General info:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops
#
# Kube resource/environment references:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops
#
# Challenges:
# https://github.com/MicrosoftDocs/azure-devops-docs/issues/3702
# - Possible path: https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/runtime-parameters.md
#
# - Multiple environment sets (prod-a, prod-b, stage-a, stage-b, ...)
#   Document as variable groups not easy (see 3702 issue above).
#   Runtime might fix with template files...
#
# - Kube credentials could be managed externally possibly, environment
# definitions don't actually need to have any content and can just be place
# holders.
#
# Environments:
# - Top level environments dont really _do_ anything.
# - They can have approvals tied to them
# - Can have business hour and branch based filters for automatic safety checks
# - Can have 'exlusive lock' to prevent overlapping deploys.

parameters:
- name: deployEnvironment
  displayName: Deploy Environment Name
  type: string
  values:
  - emarcotte-dev
  - emarcotte-stage

# No triggers for now
trigger: none
pr: none

variables:
- template: ./azure-variables/${{ parameters.deployEnvironment }}.yaml

stages:
- stage: Deploy
  jobs:
  - deployment: deployToEnvironment
    displayName: deploy application to dev

    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))

    pool:
      vmImage: Ubuntu-latest

    # This is just basic grouping of resources, doesn't _really_ afford any
    # capabilities.
    environment: $(k8sEnvironment)

    strategy:
      runOnce:
        deploy:
          steps:

          # Get the app source code from the given release
          - task: DownloadGitHubRelease@0
            inputs:
              connections: emarcotte-service-connection
              userRepository: emarcotte/deployment-app-1
              defaultVersionType: Specific Version
              version: $(appVersion)

          # Fake out a helm task for now.
          - task: HelmDeploy@0
            displayName: helm run
            inputs:
              connectionType: Kubernetes Service Connection
              kubernetesServiceEndpoint: $(k8sServiceConnection)
              namespace: $(k8sNamespace)

              command: ls

